name: atnt_project
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiodns=3.5.0=py311haa95532_0
  - aiohappyeyeballs=2.6.1=py311haa95532_0
  - aiohttp=3.12.15=py311h02ab6af_0
  - aiosignal=1.4.0=py311haa95532_0
  - annotated-types=0.6.0=py311haa95532_0
  - arrow-cpp=21.0.0=h0399227_0
  - asttokens=3.0.0=py311haa95532_0
  - attrs=24.3.0=py311haa95532_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h57dcf0c_0
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - catalogue=2.0.10=py311haa95532_0
  - certifi=2025.10.5=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_0
  - chardet=5.2.0=py311haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311haa95532_0
  - cloudpathlib=0.21.0=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - confection=0.1.5=py311hbc747e5_0
  - contourpy=1.3.1=py311h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.11=py311h885b0b7_0
  - cython-blis=1.0.1=py311h827c3e9_0
  - datasets=3.3.2=py311haa95532_0
  - debugpy=1.8.16=py311h885b0b7_0
  - decorator=5.2.1=py311haa95532_0
  - dill=0.3.8=py311haa95532_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - filelock=3.17.0=py311haa95532_0
  - fonttools=4.60.1=py311h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.5.0=py311h827c3e9_0
  - fsspec=2024.12.0=py311haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - hf-xet=1.1.8=py311h79d111c_0
  - huggingface_hub=0.34.4=py311haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.7=py311haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=py311haa95532_0
  - ipython=9.5.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - joblib=1.5.2=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py311haa95532_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - langcodes=3.5.0=py311haa95532_0
  - language-data=1.3.0=py311haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.15.0=h2300eb9_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=h83e8143_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - marisa-trie=1.3.1=py311h885b0b7_0
  - markdown-it-py=4.0.0=py311haa95532_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-base=3.10.6=py311h43afe63_0
  - matplotlib-inline=0.1.7=py311haa95532_0
  - mdurl=0.1.2=py311haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=1.3.11=py311h5810407_1
  - mkl_random=1.2.8=py311h8683371_1
  - multidict=6.7.0=py311h02ab6af_0
  - multiprocess=0.70.15=py311haa95532_0
  - murmurhash=1.0.12=py311h5da7b33_0
  - narwhals=2.7.0=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - numexpr=2.11.0=py311ha02bb35_1
  - numpy=2.3.3=py311hc2e1e29_1
  - numpy-base=2.3.3=py311hc851d2b_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py311haa95532_0
  - pandas=2.3.3=py311ha5e6156_0
  - parso=0.8.4=py311haa95532_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.3.7=py311haa95532_0
  - plotly=6.3.0=py311hbc747e5_0
  - preshed=3.0.9=py311h5da7b33_0
  - prompt-toolkit=3.0.52=py311haa95532_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - propcache=0.3.1=py311h827c3e9_0
  - protobuf=5.29.3=py311h5da7b33_0
  - psutil=7.0.0=py311h02ab6af_0
  - pure_eval=0.2.3=py311haa95532_0
  - pyarrow=21.0.0=py311ha5e6156_0
  - pycares=4.10.0=py311he29e43d_0
  - pycparser=2.23=py311haa95532_0
  - pydantic=2.12.2=py311haa95532_0
  - pydantic-core=2.41.4=py311h114bc41_0
  - pygments=2.19.1=py311haa95532_0
  - pyparsing=3.2.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h827c3e9_0
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311h885b0b7_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=27.1.0=py311h7149c55_0
  - re2=2024.07.02=h214f63a_0
  - referencing=0.30.2=py311haa95532_0
  - regex=2025.9.1=py311h02ab6af_0
  - requests=2.32.5=py311haa95532_0
  - rich=13.9.4=py311haa95532_0
  - rpds-py=0.22.3=py311h636fa0f_0
  - safetensors=0.5.3=py311h8eb67e2_0
  - scikit-learn=1.7.1=py311h3fbe716_0
  - scipy=1.16.2=py311h86a6471_0
  - seaborn=0.13.2=py311haa95532_3
  - setuptools=80.9.0=py311haa95532_0
  - shellingham=1.5.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - smart_open=7.3.1=py311haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - spacy=3.8.2=py311h214f63a_0
  - spacy-legacy=3.0.12=py311haa95532_0
  - spacy-loggers=1.0.4=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - srsly=2.5.1=py311h5da7b33_0
  - stack_data=0.6.3=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - thinc=8.3.2=py311h214f63a_1
  - threadpoolctl=3.5.0=py311h746a85d_0
  - tiktoken=0.9.0=py311h8ecf97c_0
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.0=py311hbb1481a_0
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=py311h746a85d_0
  - traitlets=5.14.3=py311haa95532_0
  - transformers=4.49.0=py311haa95532_0
  - typer=0.9.0=py311haa95532_0
  - typing-extensions=4.15.0=py311haa95532_0
  - typing-inspection=0.4.2=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wasabi=1.1.3=py311haa95532_0
  - wcwidth=0.2.13=py311haa95532_0
  - weasel=0.4.1=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winloop=0.2.2=py311h913537a_0
  - wrapt=1.17.0=py311h827c3e9_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.18.0=py311h827c3e9_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - accelerate==1.10.1
      - en-core-web-sm==3.8.0
      - mpmath==1.3.0
      - networkx==3.5
      - sympy==1.14.0
      - torch==2.9.0+cu126
      - torchinfo==1.8.0
      - torchvision==0.24.0+cu126
prefix: C:\Users\maria\.conda\envs\atnt_project
